// AUTO-GENERATED by `deno task gen-types` from scenarios/nav.py. DO NOT EDIT.
// 4 topics from the blueprint (static — no gateway).

import type { geometry_msgs, nav_msgs, sensor_msgs } from "@dimos/msgs";

export interface DimosTopics {
  "/nav/pose": geometry_msgs.PoseStamped;
  "/nav/path": nav_msgs.Path;
  "/nav/cloud": sensor_msgs.PointCloud2;
  "/nav/map": nav_msgs.OccupancyGrid;
}

export interface DimosCommands {
  "ScopeNav": {
    "navigate_to": { args: [geometry_msgs.PoseStamped]; ret: boolean };
    "start": { args: []; ret: void };
  };
}

export type TopicName = keyof DimosTopics;
export type MsgOf<K extends TopicName> = DimosTopics[K];
