// AUTO-GENERATED by `dtop gen-types`. DO NOT EDIT.
// Representative sample (a typical Go2 topic set) checked in so the app + typed hooks compile.
// Regenerate against your live gateway with:
//   deno task dtop gen-types --out app/src/dimos.topics.gen.ts

import type { geometry_msgs, nav_msgs } from "@dimos/msgs";

export interface DimosTopics {
  "/cmd_vel": geometry_msgs.Twist;
  "/map": nav_msgs.OccupancyGrid;
  "/odom": geometry_msgs.PoseStamped;
}

export type TopicName = keyof DimosTopics;
export type MsgOf<K extends TopicName> = DimosTopics[K];
