// AUTO-GENERATED by `deno task gen-types` from scenarios/nav.py, scenarios/arm.py, scenarios/cam.py, scenarios/bench.py. DO NOT EDIT.
// 12 topics · 4 command targets (static — no gateway).

import type { geometry_msgs, nav_msgs, sensor_msgs, trajectory_msgs, vision_msgs } from "@dimos/msgs";

export interface DimosTopics {
  "/nav/pose": geometry_msgs.PoseStamped;
  "/nav/path": nav_msgs.Path;
  "/nav/cloud": sensor_msgs.PointCloud2;
  "/nav/map": nav_msgs.OccupancyGrid;
  "/arm/joint_states": sensor_msgs.JointState;
  "/arm/ee_pose": geometry_msgs.PoseStamped;
  "/arm/imu": sensor_msgs.Imu;
  "/arm/trajectory": trajectory_msgs.JointTrajectory;
  "/cam/rgb": sensor_msgs.Image;
  "/cam/depth": sensor_msgs.Image;
  "/cam/points": sensor_msgs.PointCloud2;
  "/cam/detections": vision_msgs.Detection2DArray;
}

export interface DimosCommands {
  "ScopeNav": {
    "navigate_to": { args: [geometry_msgs.PoseStamped]; ret: boolean };
    "start": { args: []; ret: void };
  };
  "ScopeArm": {
    "start": { args: []; ret: void };
  };
  "ScopeCam": {
    "start": { args: []; ret: void };
  };
  "BenchSource": {
    "start": { args: []; ret: void };
  };
}

export type TopicName = keyof DimosTopics;
export type MsgOf<K extends TopicName> = DimosTopics[K];
