// Blueprint→TS codegen (live-discovery first cut). Turns the {topic,type} pairs the
// SDK discovers off the bus into a typed `DimosTopics` map, so app/CLI code gets typed
// topics with zero hand-written generics:
//
//   import type { DimosTopics } from "./dimos.topics.gen.ts";
//   const odom: DimosTopics["/odom"] = client.topic("/odom").getLatest()!;  // geometry_msgs.PoseStamped
//
// Types are sourced from the channel suffix ("<topic>#<pkg>.<Type>") and mapped onto the
// `@dimos/msgs` namespaces. A type not in @dimos/msgs (a user-defined message) falls through
// to `unknown` — it still streams + decodes at runtime via the gateway's server-json mode, so
// codegen and the zero-rebuild dynamic decode compose. A later pass can swap the live-bus
// source for static blueprint introspection (read the Python module In/Out port annotations).
import type { TopicInfo } from "../src/types.ts";
import type { CommandInfo } from "../src/transport.ts";

/** "geometry_msgs.PoseStamped" -> { pkg: "geometry_msgs", name: "PoseStamped" }; null if not a typed channel. */
function splitType(type: string): { pkg: string; name: string } | null {
  if (!type || type === "?") return null;
  const i = type.lastIndexOf(".");
  if (i <= 0 || i >= type.length - 1) return null;
  return { pkg: type.slice(0, i), name: type.slice(i + 1) };
}

/**
 * Emit a typed DimosTopics map from discovered topics. Pure (no IO) so it's unit-testable.
 * `known` = the set of type names actually in @dimos/msgs (from `getTypeNames()`); a type not in
 * it (a user-defined message) falls through to `unknown` so the generated file stays compilable.
 */
export function generateTypes(topics: readonly TopicInfo[], known: ReadonlySet<string>): string {
  const pkgs = new Set<string>();
  const rows: string[] = [];
  let untyped = 0;
  const sorted = [...topics].sort((a, b) => a.topic.localeCompare(b.topic));
  for (const t of sorted) {
    const parts = splitType(t.type);
    if (parts && known.has(t.type)) {
      pkgs.add(parts.pkg);
      rows.push(`  ${JSON.stringify(t.topic)}: ${parts.pkg}.${parts.name};`);
    } else {
      untyped++;
      rows.push(
        `  ${
          JSON.stringify(t.topic)
        }: unknown; // ${t.type} — not in @dimos/msgs (decodes at runtime)`,
      );
    }
  }
  const importLine = pkgs.size
    ? `import type { ${[...pkgs].sort().join(", ")} } from "@dimos/msgs";\n`
    : "";
  return [
    `// AUTO-GENERATED by \`generateTypes()\` (packages/topics/scripts/genTypes.ts). DO NOT EDIT.`,
    `// ${sorted.length} topics (${untyped} untyped) from live gateway discovery.`,
    ``,
    importLine,
    `export interface DimosTopics {`,
    ...(rows.length ? rows : [`  // (no topics discovered)`]),
    `}`,
    ``,
    `export type TopicName = keyof DimosTopics;`,
    `export type MsgOf<K extends TopicName> = DimosTopics[K];`,
    ``,
  ].join("\n");
}

/**
 * Emit a typed `DimosCommands` map from the gateway-advertised RPC commands (the `CommandInfo[]` the
 * SDK discovers from the `hello`). Pure (no IO), so it's unit-testable. Mirrors `generateTypes` for
 * the RPC axis (transport.ts `rpc`): `target` + `method` become checked + autocompleted today
 * (`DimosCommands[T][M]["ret"]` is indexable), while arg/return types stay `unknown` until the static
 * blueprint-introspection pass (reading the Python `@rpc` In/Out annotations) lands.
 */
export function generateCommandTypes(commands: readonly CommandInfo[]): string {
  const byTarget = new Map<string, Set<string>>();
  for (const c of commands) {
    if (!c.target || !c.method) continue;
    let methods = byTarget.get(c.target);
    if (!methods) byTarget.set(c.target, methods = new Set());
    methods.add(c.method);
  }
  const targets = [...byTarget.keys()].sort();
  const rows = targets.map((t) => {
    const methods = [...byTarget.get(t)!].sort()
      .map((m) => `    ${JSON.stringify(m)}: RpcCall;`)
      .join("\n");
    return `  ${JSON.stringify(t)}: {\n${methods}\n  };`;
  });
  return [
    `// AUTO-GENERATED by \`generateTypes()\` (packages/topics/scripts/genTypes.ts). DO NOT EDIT.`,
    `// ${commands.length} RPC command(s) from live gateway discovery.`,
    ``,
    `/** One @rpc method. args/ret are \`unknown\` until blueprint introspection types them. */`,
    `export interface RpcCall {`,
    `  args: unknown[];`,
    `  ret: unknown;`,
    `}`,
    ``,
    `export interface DimosCommands {`,
    ...(rows.length ? rows : [`  // (no rpc commands advertised)`]),
    `}`,
    ``,
    `export type RpcTarget = keyof DimosCommands;`,
    `export type RpcMethod<T extends RpcTarget> = keyof DimosCommands[T];`,
    ``,
  ].join("\n");
}
