#!/usr/bin/env python3
"""Generate the browser SDK's typed maps from a dimos blueprint — statically, no gateway/robot.

Imports a scenario blueprint (side-effect-free: class definition only, never instantiated), reads its
`PORTS` list for topic↔type pairs and reflects its `@rpc` methods for command signatures, then emits the
`dimos.topics.gen.ts` TypeScript (DimosTopics + DimosCommands) the app consumes. The client lifts the
`{args, ret}` command descriptors into a callable `modules.<Target>.<method>()` (RpcFn in client.ts).

  uv run python packages/topics/scripts/gen_types.py scenarios/nav.py
  uv run python packages/topics/scripts/gen_types.py scenarios/nav.py --out app/src/dimos.topics.gen.ts
"""

from __future__ import annotations

import argparse
import importlib.util
import inspect
from pathlib import Path
import sys
import types
import typing

# Python → TS scalar map for @rpc arg/return types.
_SCALARS = {bool: "boolean", int: "number", float: "number", str: "string"}
_UNION = (typing.Union, types.UnionType)


def _ts_type(ann: object, pkgs: set[str], *, ret: bool = False) -> str:
    """Map a Python annotation to a TS type, registering any @dimos/msgs package it needs in `pkgs`.
    Handles scalars, dimos message classes (→ `pkg.Name`), `list[X]` (→ `X[]`), and `Optional`/unions
    (→ `... | null`); anything else → `unknown`."""
    if ann is None or ann is type(None):
        return "void" if ret else "null"
    if ann is inspect.Parameter.empty:  # unannotated
        return "void" if ret else "unknown"
    if ann in _SCALARS:
        return _SCALARS[ann]  # type: ignore[index]
    name = getattr(ann, "msg_name", None)  # a dimos message class → "pkg.Name"
    if isinstance(name, str) and "." in name:
        pkgs.add(name.split(".")[0])
        return name
    origin, args = typing.get_origin(ann), typing.get_args(ann)
    if origin is list:
        return f"{_ts_type(args[0], pkgs) if args else 'unknown'}[]"
    if origin in _UNION:
        non_none = [a for a in args if a is not type(None)]
        parts = list(dict.fromkeys(_ts_type(a, pkgs) for a in non_none)) or ["unknown"]
        ts = " | ".join(parts)
        return f"{ts} | null" if len(non_none) != len(args) else ts
    return "unknown"


def _load(path: Path):
    """Import a blueprint by file path (its dir on sys.path so `common` resolves); __main__ never runs."""
    sys.path.insert(0, str(path.resolve().parent))
    spec = importlib.util.spec_from_file_location(path.stem, path)
    if not spec or not spec.loader:
        raise SystemExit(f"gen_types: cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def generate(path: Path) -> str:
    mod = _load(path)
    ports = getattr(mod, "PORTS", None)
    if not ports:
        raise SystemExit(f"gen_types: {path} has no module-level PORTS list")

    # Topics: (attr, topic, MsgClass) → topic: <pkg>.<Name> (msg_name is already "pkg.Name").
    pkgs: set[str] = set()
    topic_rows: list[str] = []
    for _attr, topic, cls in ports:
        name = getattr(cls, "msg_name", None)
        if name and "." in name:
            pkg = name.split(".")[0]
            pkgs.add(pkg)
            topic_rows.append(f'  "{topic}": {name};')
        else:
            topic_rows.append(f'  "{topic}": unknown; // {cls!r} — no msg_name')

    # Commands: the Module subclass' @rpc methods → target: { method: { args:[T..]; ret:T } }.
    from dimos.core.module import Module  # local import: only needed once dimos is on the path

    target = next(
        (
            o
            for o in vars(mod).values()
            if inspect.isclass(o)
            and issubclass(o, Module)
            and o is not Module
            and o.__module__ == mod.__name__
        ),
        None,
    )
    cmd_block = "  // (no @rpc methods)"
    if target is not None:
        method_rows: list[str] = []
        # vars(target) = methods declared ON the blueprint (skips inherited Module @rpc plumbing whose
        # annotations reference unresolved names). Read annotations straight off the signature.
        for mname, fn in sorted(vars(target).items()):
            if mname.startswith("_") or not callable(fn) or not getattr(fn, "__rpc__", False):
                continue
            sig = inspect.signature(fn)
            args = [_ts_type(p.annotation, pkgs) for n, p in sig.parameters.items() if n != "self"]
            ret = _ts_type(sig.return_annotation, pkgs, ret=True)
            method_rows.append(f'    "{mname}": {{ args: [{", ".join(args)}]; ret: {ret} }};')
        if method_rows:
            cmd_block = f'  "{target.__name__}": {{\n' + "\n".join(method_rows) + "\n  };"

    imports = f'import type {{ {", ".join(sorted(pkgs))} }} from "@dimos/msgs";\n\n' if pkgs else ""
    return (
        f"// AUTO-GENERATED by `deno task gen-types` from {path.as_posix()}. DO NOT EDIT.\n"
        f"// {len(ports)} topics from the blueprint (static — no gateway).\n\n"
        f"{imports}"
        f"export interface DimosTopics {{\n" + "\n".join(topic_rows) + "\n}\n\n"
        f"export interface DimosCommands {{\n{cmd_block}\n}}\n\n"
        f"export type TopicName = keyof DimosTopics;\n"
        f"export type MsgOf<K extends TopicName> = DimosTopics[K];\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate DimosTopics/DimosCommands from a dimos blueprint."
    )
    ap.add_argument("blueprint", help="path to a blueprint .py (e.g. scenarios/nav.py)")
    ap.add_argument("--out", help="write to this file instead of stdout")
    a = ap.parse_args()
    ts = generate(Path(a.blueprint))
    if a.out:
        Path(a.out).write_text(ts)
        print(f"gen_types: wrote {a.out}", file=sys.stderr)
    else:
        sys.stdout.write(ts)


if __name__ == "__main__":
    main()
